### PR TITLE
spearate menu files & left aligned options menus

### PR DESCRIPTION
**Pull request by Fishrock123**

### CODE REVIEW

**Comment by seiyria** [comment]
I almost feel like menuoptions should be their own class, but I'll do that refactor if necessary.

**Comment by Fishrock123** [comment]
@seiyria theres no point right now since you can't actually pass in that object. Currently it exists for optimization only.

**Comment by Fishrock123** [comment]
(well, and `this` binding)

**Comment by seiyria** [comment]
Anyway, it looks fine. I'm going to merge it.

**Pull request merged**
