### PR TITLE
Parking spaces now score, and levels position them properly

### PR DESCRIPTION
**Pull request by Fishrock123**
cc @Rabrennie & @seiyria

### CODE REVIEW

**Comment by Fishrock123** [comment]
oops, forgot to run the lint :x

**Comment by Rabrennie** [comment]
All checks have failed. RIP

**Comment by Fishrock123** [comment]
> /Users/Jeremiah/Documents/ParkyParkPark/app/js/menus/VariantMenu.js

@Rabrennie you forgot to lint on `master`

**Comment by Rabrennie** [comment]
I had no issues on my side?

**Comment by Fishrock123** [comment]
```
/Users/Jeremiah/Documents/ParkyParkPark/app/js/menus/VariantMenu.js
  3:10  error  "key" is defined but never used     no-unused-vars
  5:13  error  "levels" is defined but never used  no-unused-vars
```

Not edited here, so it must be on master. I'll just fix this in another commit.

**Comment by Fishrock123** [comment]
Looks like it was on an outdated commit on master.

**Comment by Fishrock123** [comment]
@Rabrennie All passing now.

**Comment by Fishrock123** [comment]
(Fixes https://github.com/Rabrennie/ParkyParkPark/issues/30)

**Pull request merged**
